#!/usr/bin/env python3
"""
ci/repin_floating_sources.py

Bulk re-pin tool for packages whose TERMUX_PKG_SRCURL still points at a
floating branch tarball (archive/refs/heads/...) instead of an immutable
tag or commit SHA.

This does NOT touch new packages generated by pkg-scaffold.py (that tool
already resolves things correctly since the fix). This is a one-time-ish
cleanup pass for packages that were scaffolded before the fix.

For each floating package it applies the same 3-tier resolution used in
pkg-scaffold.py:
  1. GitHub Release          -> archive/refs/tags/<tag>.tar.gz
  2. Plain Git tag           -> archive/refs/tags/<tag>.tar.gz
  3. Current commit SHA      -> archive/<full_sha>.tar.gz  (immutable)

then downloads the resolved tarball, computes its real SHA256, and updates
TERMUX_PKG_VERSION / TERMUX_PKG_SRCURL / TERMUX_PKG_SHA256 in build.sh.

Safe by default: running with no flags only PRINTS what would change.
Nothing is written to disk unless --apply is passed.

Usage:
  python ci/repin_floating_sources.py                   # dry-run, all floating packages
  python ci/repin_floating_sources.py --apply           # actually rewrite build.sh files
  python ci/repin_floating_sources.py holehe xeuledoc   # scope to specific packages
  python ci/repin_floating_sources.py --apply cupp      # apply to just one package

Set GITHUB_TOKEN (or GH_TOKEN) in the environment to raise the GitHub API
rate limit from 60/hour to 5000/hour — recommended, since each package can
take up to 3 API calls plus a tarball download.
"""

import hashlib
import json
import os
import re
import sys
import tempfile
import time
import urllib.request
import urllib.error
from pathlib import Path

PACKAGES_DIR = Path("packages")
TIMEOUT = 20
FLOATING_RE = re.compile(r"archive/refs/heads/")

R      = "\033[0m"
B      = "\033[1m"
DIM    = "\033[2m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
CYAN   = "\033[96m"
RED    = "\033[91m"

TOKEN = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")


def ok(msg):    print(f"  {GREEN}✓{R}  {msg}")
def info(msg):  print(f"  {CYAN}→{R}  {msg}")
def warn(msg):  print(f"  {YELLOW}!{R}  {msg}")
def err(msg):   print(f"  {RED}✗{R}  {msg}")
def header(msg):print(f"\n{CYAN}{B}{'─'*54}{R}\n{B}{msg}{R}")


def http_get(url: str) -> str | None:
    headers = {
        "User-Agent": "termux-app-store-repin/1.0",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
            return r.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        if e.code == 403:
            warn(f"GitHub API rate-limited (403) on {url}")
            if not TOKEN:
                warn("Set GITHUB_TOKEN in your environment to raise the rate limit.")
        return None
    except Exception:
        return None


def parse_var(build_sh: Path, var: str) -> str:
    pattern = re.compile(rf'^{var}=(.+)$', re.MULTILINE)
    content = build_sh.read_text(encoding="utf-8")
    m = pattern.search(content)
    if not m:
        return ""
    return m.group(1).strip().strip('"').strip("'")


def repo_owner_name(srcurl: str) -> tuple[str, str] | None:
    m = re.match(r"https://github\.com/([^/]+)/([^/]+)/archive/refs/heads/", srcurl)
    if not m:
        return None
    return m.group(1), m.group(2)


def resolve_pin(owner: str, repo: str) -> dict | None:
    api = f"https://api.github.com/repos/{owner}/{repo}"
    repo_url = f"https://github.com/{owner}/{repo}"

    repo_body = http_get(api)
    if not repo_body:
        return None
    try:
        data = json.loads(repo_body)
    except json.JSONDecodeError:
        return None

    default_branch = data.get("default_branch", "main")

    # Tier 1: GitHub Release
    rel_body = http_get(f"{api}/releases/latest")
    if rel_body:
        try:
            rel = json.loads(rel_body)
            tag = rel.get("tag_name", "")
            if tag:
                return {
                    "tier": "release",
                    "version": tag.lstrip("v"),
                    "srcurl": f"{repo_url}/archive/refs/tags/{tag}.tar.gz",
                    "ref": tag,
                }
        except Exception:
            pass

    # Tier 2: plain Git tag
    tags_body = http_get(f"{api}/tags")
    if tags_body:
        try:
            tags = json.loads(tags_body)
            if isinstance(tags, list) and tags:
                tag = tags[0].get("name", "")
                if tag:
                    return {
                        "tier": "tag",
                        "version": tag.lstrip("v"),
                        "srcurl": f"{repo_url}/archive/refs/tags/{tag}.tar.gz",
                        "ref": tag,
                    }
        except Exception:
            pass

    # Tier 3: commit SHA pin
    commit_body = http_get(f"{api}/commits/{default_branch}")
    if commit_body:
        try:
            commit = json.loads(commit_body)
            sha = commit.get("sha", "")
            commit_date = (commit.get("commit", {}) or {}).get("author", {}).get("date", "")
            if sha:
                date_tag = commit_date[:10].replace("-", "") if commit_date else "unknown"
                return {
                    "tier": "commit",
                    "version": f"0.0.0+{sha[:7]}",
                    "srcurl": f"{repo_url}/archive/{sha}.tar.gz",
                    "ref": f"{sha[:7]} ({date_tag})",
                }
        except Exception:
            pass

    return None


def compute_sha256(url: str) -> tuple[str, int] | None:
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "termux-app-store-repin/1.0"})
        with urllib.request.urlopen(req, timeout=120) as resp:
            h = hashlib.sha256()
            size = 0
            with tempfile.NamedTemporaryFile(delete=False) as tmp:
                while True:
                    chunk = resp.read(65536)
                    if not chunk:
                        break
                    h.update(chunk)
                    tmp.write(chunk)
                    size += len(chunk)
            return h.hexdigest(), size
    except Exception as e:
        err(f"Download failed: {e}")
        return None


def apply_changes(build_sh: Path, new_version: str, new_srcurl: str, new_sha256: str) -> None:
    content = build_sh.read_text(encoding="utf-8")

    def replace_var(content: str, var: str, new_val: str) -> str:
        pattern = re.compile(rf'^{var}=.+$', re.MULTILINE)
        return pattern.sub(f"{var}={new_val}", content, count=1)

    content = replace_var(content, "TERMUX_PKG_VERSION", new_version)
    content = replace_var(content, "TERMUX_PKG_SRCURL", new_srcurl)
    content = replace_var(content, "TERMUX_PKG_SHA256", new_sha256)
    build_sh.write_text(content, encoding="utf-8")


def find_floating_packages() -> list[str]:
    found = []
    for build_sh in sorted(PACKAGES_DIR.glob("*/build.sh")):
        srcurl = parse_var(build_sh, "TERMUX_PKG_SRCURL")
        if FLOATING_RE.search(srcurl):
            found.append(build_sh.parent.name)
    return found


def process_package(pkg: str, apply: bool) -> str:
    build_sh = PACKAGES_DIR / pkg / "build.sh"
    if not build_sh.exists():
        err(f"{pkg}: build.sh not found")
        return "error"

    srcurl = parse_var(build_sh, "TERMUX_PKG_SRCURL")
    old_version = parse_var(build_sh, "TERMUX_PKG_VERSION")
    old_sha = parse_var(build_sh, "TERMUX_PKG_SHA256")

    if not FLOATING_RE.search(srcurl):
        info(f"{pkg}: not a floating source, skipping")
        return "skipped"

    owner_repo = repo_owner_name(srcurl)
    if not owner_repo:
        warn(f"{pkg}: SRCURL doesn't match expected GitHub pattern — skipping ({srcurl})")
        return "skipped"
    owner, repo = owner_repo

    info(f"{B}{pkg}{R} — resolving {owner}/{repo}...")
    pin = resolve_pin(owner, repo)
    if not pin:
        err(f"{pkg}: could not resolve a release, tag, or commit — leaving untouched")
        return "error"

    ok(f"{pkg}: resolved via {pin['tier']} -> {pin['ref']}")

    sha_result = compute_sha256(pin["srcurl"])
    if not sha_result:
        err(f"{pkg}: failed to download resolved tarball — leaving untouched")
        return "error"
    new_sha, size = sha_result

    print(f"    {DIM}Old version : {old_version}{R}")
    print(f"    {GREEN}New version : {pin['version']}{R}")
    print(f"    {DIM}Old SRCURL  : {srcurl}{R}")
    print(f"    {GREEN}New SRCURL  : {pin['srcurl']}{R}")
    print(f"    {DIM}Old SHA256  : {old_sha}{R}")
    print(f"    {GREEN}New SHA256  : {new_sha}{R} ({size:,} bytes)")

    if apply:
        apply_changes(build_sh, pin["version"], pin["srcurl"], new_sha)
        ok(f"{pkg}: build.sh updated")
        return "fixed"
    else:
        info(f"{pkg}: dry-run only, nothing written")
        return "would_fix"


def main():
    args = sys.argv[1:]
    apply = "--apply" in args
    pkg_names = [a for a in args if not a.startswith("--")]

    if not pkg_names:
        pkg_names = find_floating_packages()

    mode = f"{RED}APPLY (writing changes){R}" if apply else f"{YELLOW}DRY-RUN (no changes written){R}"
    print(f"\n{CYAN}{B}Floating Source Re-pin Tool{R}")
    print(f"Mode: {mode}")
    print(f"{DIM}Checking {len(pkg_names)} package(s)...{R}")
    if not TOKEN:
        warn("No GITHUB_TOKEN set — using unauthenticated API (60 req/hour limit)")

    results = {"fixed": [], "would_fix": [], "skipped": [], "error": []}

    for pkg in pkg_names:
        header(f"Package: {pkg}")
        status = process_package(pkg, apply)
        results[status].append(pkg)
        time.sleep(0.5)  # be polite to the GitHub API

    print(f"\n{CYAN}{B}{'═'*30}{R}")
    print(f"{CYAN}{B}Summary{R}")
    print(f"{'─'*30}")
    if apply:
        print(f"  {GREEN}✓  Fixed        : {len(results['fixed'])}{R}")
    else:
        print(f"  {YELLOW}○  Would fix    : {len(results['would_fix'])}{R}")
    print(f"  {DIM}○  Skipped      : {len(results['skipped'])}{R}")
    print(f"  {RED}✗  Error        : {len(results['error'])}{R}")
    if results["error"]:
        for p in results["error"]:
            print(f"      {DIM}• {p}{R}")

    if not apply and (results["would_fix"]):
        print(f"\n{YELLOW}This was a dry-run. Re-run with --apply to write these changes.{R}\n")

    sys.exit(1 if results["error"] else 0)


if __name__ == "__main__":
    main()
