TERMUX_PKG_HOMEPAGE=https://github.com/djunekz/termux-app-store
TERMUX_PKG_DESCRIPTION="Encrypter Stealth Binary Builder"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux-app-store"
TERMUX_PKG_VERSION=1.0.0
TERMUX_PKG_SRCURL=https://github.com/djunekz/archive/releases/download/v${TERMUX_PKG_VERSION}/zoracrypter
TERMUX_PKG_SHA256=b0ef430b15d793100ba926c3c3082b606b7391e00cfaea0da28ccbce3446b55d
TERMUX_PKG_DEPENDS="clang, python"
TERMUX_PKG_BUILD_IN_SRC=true
